# try:
#     print(x)
# except:
#     print("an exception occured")
# else:
#     print("nothing went wrong")
# finally:
#     print("completed")

# raise
# x=-1
# if x<0:
#     raise ZeroDivisionError("sorrry no number")


# try:
#     print(x)
# except NameError:
#     print("variable x is not defined")
# except:
#     print("something else went wrong")


# try:
#     print(x)
#     raise ZeroDivisionError
# except NameError:
#     print("variable x is not defined")
# except ZeroDivisionError:
#     print("number should be not zero")

# x=int(input("enter a number"))
# if x<4:
#     raise ZeroDivisionError("sorrry no number")